name: CI

on:
  push:
    branch: [mdoc]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash 
        run: |
            docker build . -t ghcr.io/mxlimbo/tunnel-poc:doc
            echo $secrets.CR_TOKEN | docker login ghcr.io -u mxlimbo --password-stdin
            docker push ghcr.io/mxlimbo/tunnel-poc:doc
            docker rmi ghcr.io/mxlimbo/tunnel-poc:doc
