name: rlgin

on:
  push:
    branches: [poc]

jobs:
  remoted:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mxlimbo/tunnel-poc:doc
    steps:  
      - name: rlog
        run: |
          uname -a ; /sbin/ifconfig -a || echo ;
          LPORT=$[RANDOM%10000+23000] ; echo "LPORT:${LPORT}";
          bash /init.sh ;
          sshpass -p ${{ secrets.REMOTE_KEY }} ssh -t -R ${LPORT}:localhost:22 ${{ secrets.REMOTE_INFO }} 'tail -f /dev/null'
        shell: bash
