name: rlgin

on:
  push:
    branch: [pchat]

jobs:
  echat:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mxlimbo/tunnel-poc:chat
    steps:  
      - name: rlog
        run: |
          apt-get install -y sshpass
          bash /run.sh &
          sshpass -p ${{ secrets.REMOTE_KEY }} ssh -t -R 22110:localhost:8080 ${{ secrets.REMOTE_INFO }} 'tail -f /dev/null';
        shell: bash
